### PR TITLE
Add Home Page

### LINKED ISSUE #1: Home Page
Build out the elements on the "Home screen":
- Card layout + Cards
- Top heading should matching styling in design.
- "Connect to this cluster" link already opens up the drawer / the fourth card should also open up the drawer.
https://marvelapp.com/prototype/26598gag/screen/73803099

### PR DESCRIPTION
**Pull request by christiemolloy**
closes #1 

Screen Shot 2020-10-27 at 10 46 19 AM

@lboehling some questions for you
- Is there an example on PF with a special container for Tabs that gives it the same spacing that you have in the Marvel? I can add custom spacing for now but I think it might be something we are missing in PF?
- Are the cards on this page all selectable ? Should I add an eventhandler to the "Connect to this cluster" card so that when you click it, it also opens the drawer?
- there is a bug in PF that was recently fixed to fix the height of the grey background.

### CODE REVIEW

**Comment by jgiardino** [comment]
This looks great, @christiemolloy!

The only issue I see is that currently the cards don't fill the height of the Gallery grid row, in cases where their contents are different, as shown below. 

image

**Comment by lboehling** [comment]
Thanks @christiemolloy! 

> Is there an example on PF with a special container for Tabs that gives it the same spacing that you have in the Marvel? I can add custom spacing for now but I think it might be something we are missing in PF?

Do you mean the indent between the left edge and the tabs? That should be possible with using [inset tabs](https://www.patternfly.org/v4/components/tabs#inset).

> Are the cards on this page all selectable ? Should I add an eventhandler to the "Connect to this cluster" card so that when you click it, it also opens the drawer?

Yes these should be clickable. Create a topic would take you to the create topic page, and connect to this cluster should open the drawer. 

Can we swap the icons for documentation and connect to this cluster cards?

**Comment by christiemolloy** [comment]
Screen Shot 2020-10-28 at 1 35 51 PM

@jgiardino @lboehling fixed the issues mentioned in this PR:
- Cards are all equal height
- Tabs have insets
- Cards are now clickable
- Clicking on the Connect to this cluster card opens the drawer
- Clicking on the Create a topic does not yet change the tabs - captured that in this issue #17

**Comment by amysueg** [comment]
@christiemolloy I think in the above screenshot "Home" tab should be selected for the cards view (in the screenshot "Topics" is selected).

**Comment by christiemolloy** [comment]
Yep thats just the screenshot that I sent - it selects home first @amysueg

**Review by jgiardino — APPROVED** [review]
Thanks for making updates! They look great!

**Pull request merged**
